### ISSUE TITLE
Some problems in the tutorial

### ISSUE THREAD

**Issue by karajan1001** [iterative/example-dvc-experiments#6]
Need to first `dvc pull` the data before `dvc exp run` or you will get
```
$ dvc exp run
Verifying data sources in stage: 'data/images.tar.gz.dvc'
ERROR: failed to reproduce 'data/images.tar.gz.dvc': missing data 'source': data/images.tar.gz
```

**Comment by iesahin** [comment]
Yes, it's there in the hidden section: https://dvc.org/doc/start/experiments#get-the-data-set

**Comment by shcheklein** [comment]
Closing as stage, looks like not a major problem and more about docs.
