### ISSUE TITLE
Exit with code -4 on m1 MacBook pro.

### ISSUE THREAD

**Issue by karajan1001** [iterative/example-dvc-experiments#7]
This is the result of my m1 MacBook pro.
```
dvc exp run
'data/images.tar.gz.dvc' didn't change, skipping
Stage 'extract' didn't change, skipping
Running stage 'train':
> python3 src/train.py
ERROR: failed to reproduce 'dvc.yaml': failed to run: python3 src/train.py, exited with -4
```

There are two problems here.
1. the stage failed on MacBook pro with an m1 chip.
2. dvc didn't give any useful information. 

When we run the underlying training program, it would show the failure reason.
```
$ python3 src/train.py
[1]    89999 illegal hardware instruction  python3 src/train.py
$  pip3 list | grep tensorflow
tensorflow                2.5.0
tensorflow-estimator      2.5.0
```

So I guess we need:
1. some update on https://github.com/iterative/example-dvc-experiments for m1 MacBook pro
2. Better error handling for errors like this.

**Comment by efiop** [comment]
For the record: same error for me.

**Comment by iesahin** [comment]
M1 requires a custom TF installation with miniconda. I also have this issue: https://github.com/iterative/example-repos-dev/issues/93 @karajan1001 @efiop 

Will be looking at thoroughly when I return to my mac.

**Comment by shcheklein** [comment]
Here is an official instruction how to install and run it https://developer.apple.com/metal/tensorflow-plugin/ ... we can probably mention this in the docs.
